### ISSUE TITLE
GT_corpus_tokens.txt not available

### ISSUE THREAD

**Issue by ingeniom22** [ahtsham58/CRB-CRS#1]
I can't find the 'GT_corpus_tokens.txt' file. Is it possible that it's saved under a different filename or not uploaded yet?

Thanks for your help!

**Comment by ahtsham58** [comment]
Hi James,

Thanks for reaching out. The file was somehow missed. I just uploaded it at
the below path. Hope this will work out for you.

https://github.com/ahtsham58/CRB-CRS/tree/main/CRB-CRS Code/data/DialogData

*Regards*,
Ahtsham
